#!/bin/bash
exec 1>/var/log/network.synctime.log 2>&1

. /lib/esmi/local-functions.sh
. /lib/esmi/chkksml.conf

chkksmlNetworking

date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
hwclock -w
